In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from astropy import units as u
from astropy import constants as const

In [2]:
df = pd.read_csv("solar_system.csv")
df_original = df.copy()
df = df.set_index("Attribute").T
df.index.name = "Planet"
df.reset_index(inplace=True)
df.columns.name = None

In [3]:
#2.1.1.5 (Answering the Questions but only parts a, e, and g as code)
# (a) shapes
print(f"Shape before: {df_original.shape}") 
print(f"Shape after: {df.shape}") 

# (e) 
print("New Column Names:")
print(df.columns.tolist())

# (g)
df

Shape before: (20, 11)
Shape after: (10, 21)
New Column Names:
['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)', 'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)', 'Length of Day (hours)', 'Distance from Sun (10^6 km)', 'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Orbital Period (days)', 'Orbital Velocity (km/s)', 'Orbital Inclination (deg)', 'Orbital Eccentricity', 'Obliquity to Orbit (deg)', 'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons', 'Ring System?', 'Global Magnetic Field?']

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57.9,46.0,...,88.0,47.4,7.0,0.206,0.034,167,0,0,No,Yes
1,Venus,4.87,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,107.5,...,224.7,35.0,3.4,0.007,177.4,464,92,0,No,No
2,Earth,5.97,12756,5514,9.8,11.2,23.9,24.0,149.6,147.1,...,365.2,29.8,0.0,0.017,23.4,15,1,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,0.384,0.363,...,27.3,1.0,5.1,0.055,6.7,-20,0,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228.0,206.7,...,687.0,24.1,1.8,0.094,25.2,-65,0.01,2,No,No
5,Jupiter,1898,142984,1326,23.1,59.5,9.9,9.9,778.5,740.6,...,4331,13.1,1.3,0.049,3.1,-110,Unknown,95,Yes,Yes
6,Saturn,568,120536,687,9.0,35.5,10.7,10.7,1432.0,1357.6,...,10747,9.7,2.5,0.052,26.7,-140,Unknown,274,Yes,Yes
7,Uranus,86.8,51118,1270,8.7,21.3,-17.2,17.2,2867.0,2732.7,...,30589,6.8,0.8,0.047,97.8,-195,Unknown,28,Yes,Yes
8,Neptune,102,49528,1638,11.0,23.5,16.1,16.1,4515.0,4471.1,...,59800,5.4,1.8,0.010,28.3,-200,Unknown,16,Yes,Yes
9,Pluto,0.0130,2376,1850,0.7,1.3,-153.3,153.3,5906.4,4436.8,...,90560,4.7,17.2,0.244,119.5,-225,0.00001,5,No,Unknown

b) Before transposing, I had 20 rows and 11 columns. After, I have 10 rows and 21 columns.

c) set_index("Attribute").T moves the "Attribute" column to the side as labels, then flips the table so attributes become headers.  

reset_index(inplace=True) moves the planet names out of the index and back into a standard data column.

d) The new shape is not (11, 20) because the transposition process involves more than a simple swap of dimensions. When I set "Attribute" as the index, that column is moved out of the data area, reducing the column count by one before the flip. Additionally, the original first row of the CSV becomes the new column headers rather than being counted as a data row. After resetting the index to add the planet column back in, the final result reflects 10 rows (one for each planet) and 21 columns (one for each attribute plus the planet name).

f) There are 16 columns with units, including Mass (10^24kg), Diameter (km), Density (kg/m^3), Gravity (m/s^2), Escape Velocity (km/s), Rotation Period (hours), Length of Day (hours), Distance from Sun (10^6 km), Perihelion (10^6 km), Aphelion (10^6 km), Oribtal Period (days), Orbital Velocity (km/s), Orbital Inclination (degrees), Obliquity to Orbit (degrees), Mean Temperature (C), and Surface Pressure (bars).  


There are 5 columns without units: Planet, Orbital Eccientricity, Number of Moons, Ring System?, and Global Magnetic Field?

In [4]:
#2.1.2 
print("General column types:")
print(df.dtypes)

print("Specific value types in the first row:")
for col in df.columns:
    val_type = type(df[col].iloc[0])
    print(f"{col}: {val_type}")

General column types:
Planet                         object
Mass (10^24kg)                 object
Diameter (km)                  object
Density (kg/m^3)               object
Gravity (m/s^2)                object
Escape Velocity (km/s)         object
Rotation Period (hours)        object
Length of Day (hours)          object
Distance from Sun (10^6 km)    object
Perihelion (10^6 km)           object
Aphelion (10^6 km)             object
Orbital Period (days)          object
Orbital Velocity (km/s)        object
Orbital Inclination (deg)      object
Orbital Eccentricity           object
Obliquity to Orbit (deg)       object
Mean Temperature (C)           object
Surface Pressure (bars)        object
Number of Moons                object
Ring System?                   object
Global Magnetic Field?         object
dtype: object
Specific value types in the first row:
Planet: <class 'str'>
Mass (10^24kg): <class 'str'>
Diameter (km): <class 'str'>
Density (kg/m^3): <class 'str'>
Gravity (m/s^2): <class 'str'>
Escape Velocity (km/s): <class 'str'>
Rotation Period (hours): <class 'str'>
Length of Day (hours): <class 'str'>
Distance from Sun (10^6 km): <class 'str'>
Perihelion (10^6 km): <class 'str'>
Aphelion (10^6 km): <class 'str'>
Orbital Period (days): <class 'str'>
Orbital Velocity (km/s): <class 'str'>
Orbital Inclination (deg): <class 'str'>
Orbital Eccentricity: <class 'str'>
Obliquity to Orbit (deg): <class 'str'>
Mean Temperature (C): <class 'str'>
Surface Pressure (bars): <class 'str'>
Number of Moons: <class 'str'>
Ring System?: <class 'str'>
Global Magnetic Field?: <class 'str'>

2.1.2 text answers below: 

a) The individual values are strings. Although they appear as numbers, I think Pandas interprets them as text because of the original file formatting.

b) Strings cannot be used for mathematical operations or data visualization. Attempting to perform calculations on strings will probably result in errors, and plotting libraries cannot treat text as a continuous numerical scale.

In [5]:
#2.1.3 
cols_to_skip = ["Planet", "Ring System?", "Global Magnetic Field?"]
for col in df.columns:
    if col not in cols_to_skip:
        df[col] = pd.to_numeric(df[col], errors='coerce')

print(df.dtypes)

Planet                          object
Mass (10^24kg)                 float64
Diameter (km)                    int64
Density (kg/m^3)                 int64
Gravity (m/s^2)                float64
Escape Velocity (km/s)         float64
Rotation Period (hours)        float64
Length of Day (hours)          float64
Distance from Sun (10^6 km)    float64
Perihelion (10^6 km)           float64
Aphelion (10^6 km)             float64
Orbital Period (days)          float64
Orbital Velocity (km/s)        float64
Orbital Inclination (deg)      float64
Orbital Eccentricity           float64
Obliquity to Orbit (deg)       float64
Mean Temperature (C)             int64
Surface Pressure (bars)        float64
Number of Moons                  int64
Ring System?                    object
Global Magnetic Field?          object
dtype: object

2.1.3 Text Answers Below: 

a) The three types are float64, int64, and object.

b) float64: 64-bit floating-point numbers.

int64: 64-bit integers.

object: A general Pandas type used for strings or mixed text data.

c) Planet, Ring System?, and Global Magnetic Field?. These remain objects because they contain descriptive text that cannot be converted into numbers.

In [6]:
#2.2
def attach_units(col_name, unit, new_name=None):
    df[col_name] = [val * unit for val in df[col_name]]
    
    if new_name:
        df.rename(columns={col_name: new_name}, inplace=True)

In [7]:
# Picking Gravity 
unit_grav = u.m / (u.s**2)
old_name = "Gravity (m/s^2)"
new_name = "Gravity (m/s2)"

attach_units(old_name, unit_grav, new_name)

print(df[new_name])

0     3.7 m / s2
1     8.9 m / s2
2     9.8 m / s2
3     1.6 m / s2
4     3.7 m / s2
5    23.1 m / s2
6     9.0 m / s2
7     8.7 m / s2
8    11.0 m / s2
9     0.7 m / s2
Name: Gravity (m/s2), dtype: object

In [8]:
#2.3 Data Analysis
# 1. Calculating semi-major axis
peri_vals = [v * 1e6 * u.km for v in df["Perihelion (10^6 km)"]]
aphe_vals = [v * 1e6 * u.km for v in df["Aphelion (10^6 km)"]]

sma_km = [(p + a) / 2 for p, a in zip(peri_vals, aphe_vals)]

df.insert(df.columns.get_loc("Aphelion (10^6 km)") + 1, "Semi-Major Axis (km)", sma_km)

# Conversion
df["Semi-Major Axis (AU)"] = [v.to(u.AU) for v in df["Semi-Major Axis (km)"]]


df.to_csv("units.csv", index=False)
print("Saved units.csv successfully!")


df[["Planet", "Semi-Major Axis (km)", "Semi-Major Axis (AU)"]].head()

Saved units.csv successfully!

    Planet Semi-Major Axis (km)      Semi-Major Axis (AU)
0  Mercury        57900000.0 km      0.387037594379343 AU
1    Venus       108200000.0 km     0.7232723266294458 AU
2    Earth       149600000.0 km     1.0000142334913595 AU
3     Moon          384500.0 km  0.0025702237485122174 AU
4     Mars       228000000.0 km     1.5240858638772057 AU